name: Sass Compliant

on: [pull_request]

jobs:
  dart-sass:
    name: Dart Sass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - run: |
          npm install ci
          npm exec -c "sass --version"
      - run: npm run css-build
        id: build-step
      - if: always() && (steps.build-stem.outcome == 'failure')
        run: echo "The files in src/sass do not compile. You have made changes which are not valid."; exit 1
