name: Visual test

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    visual-test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 20
        - name: Install dependencies
          run: npm install
        - name: Start server
          run: npm start &
        - name: Run vusual test
          env:
            PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          run: npm run test-visual # Run the script